services:
  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    environment:
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
    ports:
      - 80:80
      - 443:443
    volumes:                                    # Storage can be either a
      - nginx_secrets:/etc/letsencrypt          # Docker managed volume (see list at the bottom)
      - ./user_conf.d:/etc/nginx/user_conf.d    # or a host mount with a relative or full path.
    depends_on:
      - n8n
  n8n:
    # 使用官方 n8n 映像
    image: docker.n8n.io/n8nio/n8n
    # 設置自動重啟策略
    restart: always
    # 暴露本地端口 5678，映射到容器內的 5678
    ports:
      - 5678:5678
    # 環境變數配置
    # environment:
    # - WEBHOOK_URL=${WEBHOOK_URL} # Webhook 的 URL，需在 .env 文件中配置
    # 掛載卷以持久化數據
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
  nginx_secrets: